function C = C_delta(dtheta1,dtheta2,dtheta3,m1,m2,theta1,theta2,theta3)
%C
%    C = C(DTHETA1,DTHETA2,DTHETA3,M1,M2,THETA1,THETA2,THETA3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026-02-15 20:48:15

t2 = cos(theta1);
t3 = cos(theta2);
t4 = cos(theta3);
t5 = sin(theta1);
t6 = sin(theta2);
t7 = sin(theta3);
C = reshape([dtheta1.*m1.*t2.*t5.*1.64025e-1+dtheta1.*m2.*t2.*t5.*6.561e-1,0.0,0.0,0.0,dtheta2.*m1.*t3.*t6.*1.64025e-1+dtheta2.*m2.*t3.*t6.*6.561e-1,0.0,0.0,0.0,dtheta3.*m1.*t4.*t7.*1.64025e-1+dtheta3.*m2.*t4.*t7.*6.561e-1],[3,3]);
end
