function M = M_delta(I1,I_motor,m1,m2,theta1,theta2,theta3)
%M
%    M = M(I1,I_motor,M1,M2,THETA1,THETA2,THETA3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026-02-15 20:48:15

t2 = cos(theta1);
t3 = cos(theta2);
t4 = cos(theta3);
t5 = sin(theta1);
t6 = sin(theta2);
t7 = sin(theta3);
t8 = t2.^2;
t9 = t3.^2;
t10 = t4.^2;
t11 = t5.^2;
t12 = t6.^2;
t13 = t7.^2;
M = reshape([I1+I_motor-m1.*t8.*4.100625e-2-m2.*t8.*1.64025e-1+m1.*t11.*4.100625e-2+m2.*t11.*1.64025e-1,0.0,0.0,0.0,I1+I_motor-m1.*t9.*4.100625e-2-m2.*t9.*1.64025e-1+m1.*t12.*4.100625e-2+m2.*t12.*1.64025e-1,0.0,0.0,0.0,I1+I_motor-m1.*t10.*4.100625e-2-m2.*t10.*1.64025e-1+m1.*t13.*4.100625e-2+m2.*t13.*1.64025e-1],[3,3]);
end
